services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: football_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - football_web

  db:
    container_name: db
    build:
      context: .
      dockerfile: Dockerfile-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db_name
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - database_volume:/var/lib/postgresql/data
    networks:
      - football_web

  nginx:
    image: nginx:latest
    container_name: football_nginx
    ports:
      - "80:80"  # перенаправляем порт 80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # монтируем файл конфигурации
    depends_on:
      - web
    networks:
      - football_web

volumes:
  database_volume:

networks:
  football_web:
