version: '3.3'

services:
  django:
    container_name: web_truck
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: >
      sh -c "
             python manage.py migrate &
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "127.0.08000:8000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgis/postgis:14-3.1
    volumes:
      - postgres_data:/var/lib/postgresql/postgis_data
    environment:
        POSTGRES_USER: user
        POSTGRES_PASSWORD: pass
        POSTGRES_DB: db_name
    ports:
      - "5432:5432"
    expose:
      - 5432

volumes:
  postgres_data: