services:
  web:
    build: .
    container_name: football_web
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      static-network:
        ipv4_address: 172.20.0.6
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: football_postgres
    environment:
      POSTGRES_DB: football
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tashkent@123
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
